import React from 'react';
import '../globals.css';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import imgSignIn from '../../public/assets/header_logo.png';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-dark-1`}>
        <div className="w-full flex flex-col items-center justify-center">
          <Image src={imgSignIn} alt="header_image" className="inline-block" />
          {children}
        </div>
      </body>
    </html>
  );
}
